sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - app/assets/javascripts/node_modules
rvm:
  - 2.3.0
before_script:
  - echo "Rspec setup"
  - export RAILS_ENV=test
  - cp .example-env .env
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - echo "node setup"
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
script:
  - bundle exec rspec && bundle exec brakeman -q -z && npm test
addons:
  code_climate:
    repo_token: 479d3bf56798fbc7fff3fc8151a5ed09e8ac368fd5af332c437b9e07dbebb44e
