development:
  min_messages: WARNING
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  encoding: unicode
  database: issad_development
  pool: 5
  username: postgres
  password: "3112"

test:
  min_messages: WARNING
  adapter: postgresql
  host: ec2-54-243-217-241.compute-1.amazonaws.com
  port: 5432
  encoding: unicode
  database: dbct9hosrirq2h
  pool: 5
  username: tkbwavghytilon
  password: "To6z-64f1Lr3LqpWrcLBPG2Xdv"

production:
  min_messages: WARNING
  adapter: postgresql
  host: ec2-54-243-217-241.compute-1.amazonaws.com
  port: 5432
  encoding: unicode
  database: dbct9hosrirq2h
  pool: 5
  username: tkbwavghytilon
  password: "To6z-64f1Lr3LqpWrcLBPG2Xdv"
