development:
  min_messages: WARNING
  adapter: postgresql
  host: ec2-54-243-188-58.compute-1.amazonaws.com
  port: 5432
  encoding: unicode
  database: da81fvorvn5pp9
  pool: 5
  username: yolhqgtlivenrk
  password: "oi_EAZwbXboYjqB_9tWPh2x5YS"

test:
  min_messages: WARNING
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  encoding: unicode
  database: metamap002_test
  pool: 5
  username: postgres
  password: "3112"

production:
  min_messages: WARNING
  adapter: postgresql
  host: ec2-54-243-188-58.compute-1.amazonaws.com
  port: 5432
  encoding: unicode
  database: da81fvorvn5pp9
  pool: 5
  username: yolhqgtlivenrk
  password: "oi_EAZwbXboYjqB_9tWPh2x5YS"
